# Generated by Django 3.2.4 on 2021-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('image', models.FileField(upload_to='files/')),
                ('description', models.TextField(default='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
