# Generated by Django 3.2.4 on 2021-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlogVideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.TextField(max_length=100)),
                ('image', models.FileField(upload_to='files')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
