# Generated by Django 3.2.4 on 2021-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210702_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='date',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='date',
            field=models.DateField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
