# Generated by Django 3.2.4 on 2021-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20210702_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
