# Generated by Django 3.2.4 on 2021-07-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20210702_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagemodel',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='blogimagemodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blogvideosmodel',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='blogvideosmodel',
            name='text',
        ),
        migrations.CreateModel(
            name='VideoCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_comment', models.DateField(auto_now=True)),
                ('image_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.blogimagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_comment', models.DateField(auto_now=True)),
                ('image_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.blogimagemodel')),
            ],
        ),
    ]
