# Generated by Django 3.2.4 on 2021-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20210703_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecommentsmodel',
            name='image_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videocommentsmodel',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
