# Generated by Django 3.2.4 on 2021-07-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20210703_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocommentsmodel',
            old_name='image_id',
            new_name='video_id',
        ),
    ]
