# Generated by Django 3.2.4 on 2021-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20210706_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogvideosmodel',
            name='image',
            field=models.FileField(upload_to='files/'),
        ),
    ]
