# Generated by Django 3.2.4 on 2021-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_blogvideosmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecommentsmodel',
            name='nick_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videocommentsmodel',
            name='nick_name',
            field=models.TextField(default=''),
        ),
    ]
