# Generated by Django 3.2.4 on 2021-07-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_auto_20210709_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagecommentsmodel',
            name='nick_name',
            field=models.TextField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='videocommentsmodel',
            name='nick_name',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
